apiVersion: v1
kind: Secret
metadata:
  name: vupqh-aws-secret
  namespace: default
type: Opaque
data:
  AWS_REGION: dXMtZWFzdC0x
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_PROFILE: ZGVmYXVsdA==
  config: |
    W2RlZmF1bHRdCnJlZ2lvbiA9IHVzLWVhc3QtMQpvdXRwdXQgPSBqc29u
  credentials: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQVNJQVhaM1VLRkQySFdOQVZBNFIKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gZy9xbFZnNGhzdDNWem02SFRrU3dGekhYcnVPdkJDOFQ5UUxOZXRjVgphd3Nfc2Vzc2lvbl90b2tlbiA9IEZ3b0daWEl2WVhkekVEMGFEQUJMczlrTzA0by9ZMVVmV3lMVkFZOExITGtGSTNxUVB3cWtnUUNPUTYxNGt4WjdDY21mSzBVUG13NTh6Y3NIeDhrSXJyVXkxZXZLRXRRd3RUQ2pod2NGZXFISDhtMzRkUm9PMkQvckY0OUdBb29LVVpTbUVrcUZPYnFnNjQyTTNYTDcxTkxtV1Y5aHBObUg0M3dJdEFsa0pvYUdJN1lHSXpUK3VZb2tzaCtYQXNFZ1lITTBrdStUQlJYbWxvc2s3cDNSQzM5dmo0RFJ2T3VlQ3VtYXkrV3VHclhnN3R1NjBDTC9FLzJZOCtmZ1Z1YTMxS2lSVEZJSyt5Skk2SklPYlZ3MkpYNmRkMkR0aVhhYmdwcDluK2loWGUrQVRxNUJWZDNTWHJ2T2ZxZm1Kb0tIQUNpc3hMbW9Cakl0WFIvYUtkOTdZemtHVVJsRFBZV3J3NGtUZ05UUjg5RGVScGpKeU9rSGtBMWwyTkhxOG43Kzk4NzBxYzZ6