apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vupqh
  labels:
    app: frontend-vupqh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-vupqh
  template:
    metadata:
      labels:
        app: frontend-vupqh
    spec:
      containers:
      - name: udagram-frontend
        image: vupqh/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1m"
          requests:
            cpu: "1m"